mdapiunpkg/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>UF_Event_Time__c</fullName>
        <description>Event Start Time</description>
        <inlineHelpText>Event Start Time. For events with recurrences, use the date of the first event.</inlineHelpText>
        <label>UF_Event Time</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

mdapiunpkg/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>UF_Total_Attended__c</fullName>
        <label>UF Total Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UF_Total_in_Party_Number__c</fullName>
        <formula>value(text(UF_Total_in_Party__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UF_Total in Party Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

mdapiunpkg/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Admission_Interest__c</fullName>
        <label>Admission Interest</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Freshman Admission</fullName>
                </value>
                <value>
                    <fullName>Transfer Admission</fullName>
                </value>
                <value>
                    <fullName>Graduate Admission</fullName>
                </value>
                <value>
                    <fullName>Professional School Admission</fullName>
                </value>
                <value>
                    <fullName>I have applied to the University of Florida</fullName>
                </value>
                <value>
                    <fullName>I have been admitted to the University of Florida</fullName>
                </value>
                <value>
                    <fullName>I do not intend to apply</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Entry_Term__c</fullName>
        <label>Entry Term</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Fall</fullName>
                </value>
                <value>
                    <fullName>Spring</fullName>
                </value>
                <value>
                    <fullName>Summer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Entry_Year__c</fullName>
        <label>Entry Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>High_School_Graduation_Year__c</fullName>
        <label>High School Graduation Year</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2005</fullName>
                </value>
                <value>
                    <fullName>2006</fullName>
                </value>
                <value>
                    <fullName>2007</fullName>
                </value>
                <value>
                    <fullName>2008</fullName>
                </value>
                <value>
                    <fullName>2009</fullName>
                </value>
                <value>
                    <fullName>2010</fullName>
                </value>
                <value>
                    <fullName>2011</fullName>
                </value>
                <value>
                    <fullName>2012</fullName>
                </value>
                <value>
                    <fullName>2013</fullName>
                </value>
                <value>
                    <fullName>2014</fullName>
                </value>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
                <value>
                    <fullName>2021</fullName>
                </value>
                <value>
                    <fullName>2022</fullName>
                </value>
                <value>
                    <fullName>2023</fullName>
                </value>
                <value>
                    <fullName>2024</fullName>
                </value>
                <value>
                    <fullName>2025</fullName>
                </value>
                <value>
                    <fullName>2026</fullName>
                </value>
                <value>
                    <fullName>2027</fullName>
                </value>
                <value>
                    <fullName>2028</fullName>
                </value>
                <value>
                    <fullName>2029</fullName>
                </value>
                <value>
                    <fullName>2030</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Major_Interest_1__c</fullName>
        <label>Major Interest 1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Advertising</fullName>
                </value>
                <value>
                    <fullName>Aerospace Engineering</fullName>
                </value>
                <value>
                    <fullName>African American Studies</fullName>
                </value>
                <value>
                    <fullName>Agricultural Education and Communication</fullName>
                </value>
                <value>
                    <fullName>Agricultural Operations Management</fullName>
                </value>
                <value>
                    <fullName>Animal Science</fullName>
                </value>
                <value>
                    <fullName>Anthropology</fullName>
                </value>
                <value>
                    <fullName>Applied Physiology and Kinesiology</fullName>
                </value>
                <value>
                    <fullName>Architecture</fullName>
                </value>
                <value>
                    <fullName>Art</fullName>
                </value>
                <value>
                    <fullName>Art Education</fullName>
                </value>
                <value>
                    <fullName>Art History</fullName>
                </value>
                <value>
                    <fullName>Astronomy</fullName>
                </value>
                <value>
                    <fullName>Athletic Training</fullName>
                </value>
                <value>
                    <fullName>Biological Engineering</fullName>
                </value>
                <value>
                    <fullName>Biology</fullName>
                </value>
                <value>
                    <fullName>Biomedical Engineering</fullName>
                </value>
                <value>
                    <fullName>Botony</fullName>
                </value>
                <value>
                    <fullName>Business Administration - General Studies</fullName>
                </value>
                <value>
                    <fullName>Chemical Engineering</fullName>
                </value>
                <value>
                    <fullName>Chemistry</fullName>
                </value>
                <value>
                    <fullName>Civil Engineering</fullName>
                </value>
                <value>
                    <fullName>Classical Studies</fullName>
                </value>
                <value>
                    <fullName>Communication Sciences and Disorders</fullName>
                </value>
                <value>
                    <fullName>Computer Engineering</fullName>
                </value>
                <value>
                    <fullName>Computer Science</fullName>
                </value>
                <value>
                    <fullName>Construction Management</fullName>
                </value>
                <value>
                    <fullName>Criminology and Law</fullName>
                </value>
                <value>
                    <fullName>Dance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Major_Interest_2__c</fullName>
        <label>Major Interest 2</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Advertising</fullName>
                </value>
                <value>
                    <fullName>Aerospace Engineering</fullName>
                </value>
                <value>
                    <fullName>African American Studies</fullName>
                </value>
                <value>
                    <fullName>Agricultural Education and Communication</fullName>
                </value>
                <value>
                    <fullName>Agricultural Operations Management</fullName>
                </value>
                <value>
                    <fullName>Animal Science</fullName>
                </value>
                <value>
                    <fullName>Anthropology</fullName>
                </value>
                <value>
                    <fullName>Applied Physiology and Kinesiology</fullName>
                </value>
                <value>
                    <fullName>Architecture</fullName>
                </value>
                <value>
                    <fullName>Art</fullName>
                </value>
                <value>
                    <fullName>Art Education</fullName>
                </value>
                <value>
                    <fullName>Art History</fullName>
                </value>
                <value>
                    <fullName>Astronomy</fullName>
                </value>
                <value>
                    <fullName>Athletic Training</fullName>
                </value>
                <value>
                    <fullName>Biological Engineering</fullName>
                </value>
                <value>
                    <fullName>Biology</fullName>
                </value>
                <value>
                    <fullName>Biomedical Engineering</fullName>
                </value>
                <value>
                    <fullName>Botony</fullName>
                </value>
                <value>
                    <fullName>Business Administration - General Studies</fullName>
                </value>
                <value>
                    <fullName>Chemical Engineering</fullName>
                </value>
                <value>
                    <fullName>Chemistry</fullName>
                </value>
                <value>
                    <fullName>Civil Engineering</fullName>
                </value>
                <value>
                    <fullName>Classical Studies</fullName>
                </value>
                <value>
                    <fullName>Communication Sciences and Disorders</fullName>
                </value>
                <value>
                    <fullName>Computer Engineering</fullName>
                </value>
                <value>
                    <fullName>Computer Science</fullName>
                </value>
                <value>
                    <fullName>Construction Management</fullName>
                </value>
                <value>
                    <fullName>Criminology and Law</fullName>
                </value>
                <value>
                    <fullName>Dance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

force-app/main/default/classes/UFToursController.cls
public with sharing class UFToursController {
    public class SelectOption {
        public SelectOption(String value, String label) {
            this.value = value;
            this.label = label;
            this.disabled = false;
            this.escapeItem = false;
        }
    
        public SelectOption(String value, String label, Boolean isDisabled) {
            this.value = value;
            this.label = label;
            this.disabled = isDisabled;
            this.escapeItem = false;
        }
    
        @AuraEnabled
        public String label { get;set; }
        @AuraEnabled
        public String value { get;set; }
        @AuraEnabled
        public Boolean disabled { get;set; }
        @AuraEnabled
        public Boolean escapeItem { get;set; }
    
    }
    @AuraEnabled
    public static List<Campaign> getMatchingCampaignNames(Integer selectedYear, Integer selectedMonth, Integer selectedDay, String selectedCampaign) {
        Integer intYear = Integer.valueOf(selectedYear);
        Integer intMonth = Integer.valueOf(selectedMonth);
        Integer intDay = Integer.valueOf(selectedDay);
        Date queryDate = Date.newInstance(intYear, intMonth, intDay);
        List<Campaign> returnList =  [SELECT Id, Name 
                                        FROM Campaign 
                                        WHERE DAY_ONLY(Campaign.UF_Event_Time__c) = :queryDate 
                                          AND Campaign.Type = 'Campus Tour'
                                        ORDER BY Campaign.UF_Event_Time__c];
        system.debug('Campaigns...');
        system.debug(returnList);
        return returnList;
    }
    @AuraEnabled
    public static Lead initiateLead() {
        Lead newLead = new Lead();
        newLead.CountryCode = 'United States';
        return newLead;
    }
    @AuraEnabled
    public static List<SelectOption> getStates() {
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult fieldResult = Lead.StateCode.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
    
        for (Schema.PicklistEntry pe : SObjectType.Lead.fields.StateCode.getPicklistValues()) {
            if (pe.getLabel() == 'US') {
                options.add(new SelectOption(pe.getValue(), pe.getLabel()));
            }
        }
        
        return options;
    }
    @AuraEnabled
    public static List<SelectOption> getCountries() {
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult fieldResult = Lead.CountryCode.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
    
        for (Schema.PicklistEntry f: ple) {
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        }       
        
        return options;
    }
    @AuraEnabled
    public static List<SelectOption> getAdmissionInterests() {
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult fieldResult = Lead.Admission_Interest__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
    
        for (Schema.PicklistEntry f: ple) {
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        }       
        
        return options;
    }
    @AuraEnabled
    public static List<CampaignMember> getUFToursByType(Integer campMonth, Integer campDay, Integer campYear, String campaignId) {
        system.debug(campMonth + '-' + campDay + '-' + campYear + '  -  ' + campaignId);
        DATETIME queryDateTime = DATETIME.now();
        Integer intYear = Integer.valueOf(campYear);
        Integer intMonth = Integer.valueOf(campMonth);
        Integer intDay = Integer.valueOf(campDay);

        List<CampaignMember> campaigns = new List<CampaignMember>();
        DATE queryDate = Date.newInstance(intYear, intMonth, intDay);
        
        if(campMonth == null || campDay == null || campYear == null) {
            queryDateTime = DATE.today(); 
        }
        else {
        	queryDateTime = DATE.newInstance(intYear, intMonth, intDay);   
        }
        if(campaignId == '' || campaignId == null) {
            campaigns = [SELECT FirstName, LastName, Status, UF_Total_Attended__c,
                        UF_Total_in_Party_Number__c, City, State, Comments__c,
                        Lead.Entry_Term__c, Lead.Entry_Year__c, Lead.High_School_Graduation_Year__c, 
                        Lead.Major_Interest_1__c, Lead.Major_Interest_2__c, Lead.Major_Interest_3__c, 
                        Lead.Admission_Interest__c,
                        Campaign.Id, Campaign.Name, Campaign.UF_Event_Time__c, Campaign.UF_Event_End_Time__c
                   FROM CampaignMember 
                   WHERE DAY_ONLY(Campaign.UF_Event_Time__c) = :queryDate
                     AND Campaign.Type = 'Campus Tour'
                   ORDER BY LastName, FirstName
                ];
        } else {
            ID idCamp = campaignId;
            system.debug(idCamp);
            campaigns = [SELECT FirstName, LastName, Status, UF_Total_Attended__c,
                        UF_Total_in_Party_Number__c, City, State, Comments__c,
                        Lead.Entry_Term__c, Lead.Entry_Year__c, Lead.High_School_Graduation_Year__c, 
                        Lead.Major_Interest_1__c, Lead.Major_Interest_2__c, Lead.Major_Interest_3__c, 
                        Lead.Admission_Interest__c,
                        Campaign.Id, Campaign.Name, Campaign.UF_Event_Time__c, Campaign.UF_Event_End_Time__c
                   FROM CampaignMember 
                   WHERE Campaign.ID = :idCamp
                   ORDER BY LastName, FirstName
                ];
        }
        return campaigns;
    }
    @AuraEnabled
    public static List<SelectOption> getMemberStatuses() {
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult fieldResult = CampaignMember.Status.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        Set<String> tourStatuses = new Set<String>();
        tourStatuses.add('Attended');
        tourStatuses.add('No Show');
        tourStatuses.add('Cancelled');
        options.add(new SelectOption('Select Status', ''));
        
        for( Schema.PicklistEntry f : ple)
        {
            if(tourStatuses.contains(f.getLabel()) || (f.getLabel() == '')) {
            	options.add(new SelectOption(f.getLabel(), f.getValue(), false));
                system.debug(f.getValue() + ' is available');
            } else {
            	options.add(new SelectOption(f.getLabel(), f.getValue(), true));
                system.debug(f.getValue() + ' is disabled');
            }
        }       
        
        return options;
    }
    @AuraEnabled
    public static Id getCampaignId() {
        String idFromStr = '70141000000bblW';
        Id finalId = Id.valueOf(idFromStr);
		Id idForCampaign = [SELECT Id FROM Campaign WHERE Id = :finalId].ID;     
        return idForCampaign;
    }    
    @AuraEnabled
    public static void addCampaignMember(Lead pLead, String pCampaignId, Integer pNumAttending) {        
        Lead newLead = new Lead();
        newLead.FirstName = pLead.FirstName;
        newLead.LastName = pLead.LastName;
        newLead.Company = pLead.LastName + ' Administrative Account';
        newLead.Email = pLead.Email;
        newLead.Admission_Interest__c = pLead.Admission_Interest__c;
        newLead.StateCode = pLead.StateCode;
        newLead.City = pLead.City;
        
        try {
        	insert newLead;
            system.debug(newLead);
        } catch(Exception e) {
            system.debug(e);
        }
        
        CampaignMember member = new CampaignMember();
        member.CampaignId = pCampaignId;
        member.LeadId = newLead.Id;
        member.UF_Total_Attended__c = Integer.valueOf(pNumAttending);
        member.Status = 'Attended';
        
        try {
        	insert member;
            system.debug(member);
        } catch(Exception e) {
            system.debug(e);
        }
    }
    @AuraEnabled
    public static void updateCampaignMember(CampaignMember campaignMember) {
        try {
        	update campaignMember;
            system.debug(campaignMember);
        } catch(Exception e) {
            system.debug(e);
        }
    }
}