mdapiunpkg/objects/Character__c.object
<CustomObject>
    <fields>
        <fullName>PcNpc__c</fullName>
        <description>Is this a PC or NPC</description>
        <label>PcNpc</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>PC</fullName>
                </value>
                <value>
                    <fullName>NPC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The region in which the character currently resides.</description>
        <label>Region</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Characters</relationshipLabel>
        <relationshipName>Characters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Character</label>
    <nameField>
        <label>Character Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Characters</pluralLabel>
    <recordTypes>
        <fullName>Base</fullName>
        <active>true</active>
        <description>Base character template to use to reference when creating encounters.</description>
        <label>Base</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapiunpkg/classes/GMSCharacterByRegion.cls
public class GMSCharacterByRegion  {
    @AuraEnabled
    public static List<Character__c> getCharactersByRegion(Id regionId) {
		RecordType recTypeAPIName = [SELECT Id, Name, DeveloperName FROM RecordType WHERE DeveloperName = 'Base' AND SobjectType = 'Character__c' LIMIT 1]; 
	
		List<Character__c> characters = [SELECT Id FROM Character__c WHERE Region__c = :regionId AND PcNpc__c = 'NPC'];
        
		return characters;
	}
}