mdapiunpkg/objects/Character__c.object
<CustomObject>
    <label>Character</label>
    <nameField>
        <label>Character Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Characters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapiunpkg/objects/Encounter__c.object
<CustomObject>
    <label>Encounter</label>
    <nameField>
        <label>Encounter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapiunpkg/objects/Encounter_NPC__c.object
<CustomObject>
    <fields>
        <fullName>Character__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Character</label>
        <referenceTo>Character__c</referenceTo>
        <relationshipLabel>Encounter NPCs</relationshipLabel>
        <relationshipName>Encounter_NPCs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Encounter NPCs</relationshipLabel>
        <relationshipName>Encounter_NPCs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Encounter NPC</label>
    <nameField>
        <label>Encounter NPCs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Encounter NPCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapiunpkg/objects/Memo__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Id__c</fullName>
        <description>Salesforce Id of Parent record</description>
        <label>Parent Id</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Object_Type__c</fullName>
        <label>Parent Object Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Archetype__c</fullName>
                </value>
                <value>
                    <fullName>Archetype_Power__c</fullName>
                </value>
                <value>
                    <fullName>Character__c</fullName>
                </value>
                <value>
                    <fullName>Character_Power__c</fullName>
                </value>
                <value>
                    <fullName>Custom_Data__c</fullName>
                </value>
                <value>
                    <fullName>Effect__c</fullName>
                </value>
                <value>
                    <fullName>Encounter__c</fullName>
                </value>
                <value>
                    <fullName>Encounter_NPC__c</fullName>
                </value>
                <value>
                    <fullName>Plot Point</fullName>
                </value>
                <value>
                    <fullName>Region</fullName>
                </value>
                <value>
                    <fullName>RPG Campaign</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Memo</label>
    <nameField>
        <label>Memo Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapiunpkg/classes/GMSNotesListController.cls
public class GMSNotesListController {
    @AuraEnabled
    public static List<Memo__c> getNotes(Id parentId) {
        Schema.SObjectType result = parentId.getSobjectType();

        List<Object> notes = new List<Object> ();
		List<Encounter_NPC__c> children = new List<Encounter_NPC__c>();
		List<Object> childNotes = new List<Object>();
		Set<Id> childIds = new Set<Id>();

		List<Memo__c> finalNotes = new List<Memo__c>();
		Set<Id> noteParentIds = new Set<Id>();

		List<Encounter__c> eNotes = new List<Encounter__c>();
		List<Character__c> cNotes = new List<Character__c>();
		List<Account> aNotes = new List<Account>();

        if(result == Schema.Encounter__c.SObjectType) {
			for(Encounter__c e : [SELECT Id FROM Encounter__c WHERE Id = :parentId]) {
				noteParentIds.add(e.Id);
			}

			children = [SELECT Character__r.Id FROM Encounter_NPC__c WHERE Encounter__r.Id = :parentId];
			for( Encounter_NPC__c o : children) {
				noteParentIds.add(o.Character__c);
			}
			for(Character__c c : [SELECT Id FROM Character__c WHERE Id IN :childIds]) {
				noteParentIds.add(c.Id);
			}
			System.debug(noteParentIds);
        } else if(result == Schema.Account.SObjectType) {
			for(Account a : [SELECT Id FROM Account WHERE Id = :parentId]) {
				noteParentIds.add(a.Id);
			}
			System.debug(noteParentIds);
        }

		finalNotes = [SELECT Id, Name, Parent_Object_Type__c, Parent_Id__c FROM Memo__c WHERE Parent_Id__c IN :noteParentIds];

        return finalNotes;
    }
}