mdapiunpkg/objects/Character__c.object
<CustomObject>
    <fields>
        <fullName>Initiative_Order__c</fullName>
        <description>Used to record initiative for instance of encounter.</description>
        <label>Initiative Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Character</label>
    <nameField>
        <label>Character Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Characters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapiunpkg/objects/Encounter__c.object
<CustomObject>
    <label>Encounter</label>
    <nameField>
        <label>Encounter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapiunpkg/objects/Encounter_NPC__c.object
<CustomObject>
    <fields>
        <fullName>Character__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Character</label>
        <referenceTo>Character__c</referenceTo>
        <relationshipLabel>Encounter NPCs</relationshipLabel>
        <relationshipName>Encounter_NPCs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Encounter NPCs</relationshipLabel>
        <relationshipName>Encounter_NPCs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Encounter NPC</label>
    <nameField>
        <label>Encounter NPCs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Encounter NPCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GMSEncounterCharList.cls
public class GMSEncounterCharList {
    
    @AuraEnabled
    public static List<Character__c> getEncounterCharacterList(Id encounterId) {
        List<Character__c> charList = new List<Character__c>();
        List<Encounter_NPC__c> charIdList = [SELECT Character__r.Id FROM Encounter_NPC__c WHERE Encounter__r.Id=:encounterId ORDER BY Character__r.Initiative_Order__c]; 
        
        if(charIdList != null) {
            for(Encounter_NPC__c e : charIdList) {
                Character__c newChar = new Character__c();
                newChar.Id = e.Character__r.Id;
                if(newChar.Id != null) {
                    charList.add(newChar);
                }
            }
        }
        
        return charList;
    }
}