mdapiunpkg/objects/Custom_Data__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Is this a table name, column name, or record value?</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Table</fullName>
                </value>
                <value>
                    <fullName>Column</fullName>
                </value>
                <value>
                    <fullName>Record</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Custom Data</label>
    <nameField>
        <label>Custom Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapiunpkg/classes/GMSCustomDataDesignResourcePickList.cls
global class GMSCustomDataDesignResourcePickList extends VisualEditor.DynamicPickList {
   global override VisualEditor.DataRow getDefaultValue(){
       VisualEditor.DataRow defaultValue = new VisualEditor.DataRow('Spell Damage','a0G4100000kupTMEAY');
       return defaultValue;
   }
   global override VisualEditor.DynamicPickListRows getValues() {   
       VisualEditor.DynamicPickListRows  myValues = new VisualEditor.DynamicPickListRows();
       for(Custom_Data__c cd : [SELECT Id, Name FROM Custom_Data__c WHERE Type__c = 'Table']) {
           myValues.addRow(new VisualEditor.DataRow(cd.Name, cd.Id));
       }
       return myValues;
   }
}