mdapiunpkg/objects/Custom_Data__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <description>Order in which values appear in a row.</description>
        <label>Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Table__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Table</label>
        <referenceTo>Custom_Data__c</referenceTo>
        <relationshipLabel>Custom Data (Parent Table)</relationshipLabel>
        <relationshipName>Custom_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Row_Number__c</fullName>
        <description>Row number to unite columns for a particular row.</description>
        <label>Row Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Is this a table name, column name, or record value?</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Table</fullName>
                </value>
                <value>
                    <fullName>Column</fullName>
                </value>
                <value>
                    <fullName>Record</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Custom Data</label>
    <nameField>
        <label>Custom Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapiunpkg/classes/GMSCustomDataCtrl.cls
public with sharing class GMSCustomDataCtrl {
	@AuraEnabled
    public static List<Custom_Data__c> getTables() {
        return [SELECT Id, Name FROM Custom_Data__c WHERE Type__c = 'Table'];
    }
	@AuraEnabled
    public static List<Custom_Data__c> getTableColumns(Id tableId) {
        return [SELECT Id, Name, Order__c FROM Custom_Data__c WHERE Parent_Table__c = :tableId AND Type__c = 'Column' ORDER BY Order__c];
    }
	@AuraEnabled
    public static List<Custom_Data__c> getTableRows(Id tableId) {
        return [SELECT Id, Name, Row_Number__c, Order__c FROM Custom_Data__c WHERE Parent_Table__c = :tableId AND Type__c = 'Record' ORDER BY Row_Number__c, Order__c];
    }
}