mdapiunpkg/objects/Encounter__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Encounters</relationshipLabel>
        <relationshipName>Encounters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Encounter</label>
    <nameField>
        <label>Encounter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <recordTypes>
        <fullName>Base</fullName>
        <active>true</active>
        <description>The record used to reference when constructing an encounter.</description>
        <label>Base</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapiunpkg/classes/GMSEncounterList.cls
public class GMSEncounterList  {
    @AuraEnabled
    public static List<Encounter__c> getBaseEncountersByRegion(Id regionId) {
		RecordType recTypeAPIName = [SELECT Id, Name, DeveloperName FROM RecordType WHERE DeveloperName = 'Base' AND SobjectType = 'Encounter__c' LIMIT 1]; 
	
		List<Encounter__c> encounters = [SELECT Id FROM Encounter__c WHERE Region__c = :regionId];
        
		return encounters;
	}
}